Add err tips when open error.
ntop/nDPI pull request #1515
Opened 2022-04-15 04:03 UTC by Gowa2017

When open a device, we do not know why we failed.

2022-04-19 07:22 UTC, IvanNardi commented on src/lib/protocols/wzry.c
> +                             /* ndpi_protocol_type_t protocol_type */) {
I know that you have probably copied this prototype from some other file, but you can completely remove the third parameter

2022-04-19 07:25 UTC, IvanNardi requested changes
Could you add some traces as example with both TCP and UDP flows, please?

2022-04-19 07:25 UTC, IvanNardi commented on src/lib/protocols/wzry.c
> +    fprintf(stderr,"%s -> %d",flow->saddr, flow->saddr);
All these fprintf calls should be removed

2022-04-19 07:25 UTC, IvanNardi commented on src/lib/protocols/wzry.c
> +        fprintf(stderr,"found WZRY\n");
As before

2022-04-19 07:25 UTC, IvanNardi commented on src/lib/protocols/wzry.c
> +        fprintf(stderr,"found WZRY\n");
Same

2022-04-19 07:25 UTC, IvanNardi commented on src/lib/protocols/wzry.c
> +        NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_OR_UDP_WITH_PAYLOAD,
I am pretty sure that `NDPI_SELECTION_BITMASK_PROTOCOL_V4_V6_TCP_OR_UDP_WITH_PAYLOAD_WITHOUT_RETRANSMISSION` is better

2022-04-20 12:15 UTC, Gowa2017 commented
I'sorry , I only want to push the error tip.

But  when I test WZRY protocol, I pushed tje test code, so I will close the pr.

2022-04-20 12:15 UTC, closed without merging