LDAP: rewrite dissection
ntop/nDPI pull request #1649
Opened 2022-07-07 09:45 UTC by IvanNardi

2022-07-07 13:43 UTC, utoni requested changes

2022-07-07 13:43 UTC, utoni commented on src/lib/protocols/ldap.c
> +static int asn1_ber_length(const unsigned char *payload, int payload_len, u_int16_t *value_len)
Remembered that I've wrote a similar function for Kerberos some time ago. Why not use that one instead of creating code duplicates?

2022-07-07 14:50 UTC, IvanNardi commented on src/lib/protocols/ldap.c
> +static int asn1_ber_length(const unsigned char *payload, int payload_len, u_int16_t *value_len)
It makes sense...

2022-07-08 10:49 UTC, utoni approved these changes
:+1:

2022-07-08 10:50 UTC, merged