printed xor_mapped_address
ntop/nDPI pull request #2016
Opened 2023-06-20 14:28 UTC by carloleo

the output has been checked by running `./ndpiReader -i whatsapp_stun_orig_call.pcapng`. 
PCAP file [here](https://github.com/ntop/nDPI/files/1784544/whatsapp_stun_orig_call.zip).

![output](https://github.com/ntop/nDPI/assets/50950273/fa4efa82-f09d-4351-9d68-ab29d7d11d6f)

2023-06-20 15:52 UTC, IvanNardi requested changes
@carloleo thank for your code. I agree that extracting this attribute might be useful. However there are two major issues with your PR.

1) Attributes (in this case, xor_mapped_address) are never directly printed by the library. We need to save them in `struct ndpi_flow_struct` and then: a) print them in `ndpiReader` code; b) add them to the json export. You can take a look at any HTTP/TLS metadata for some examples

2) The code parsing the STUN attributes list is already there in `stun.c` around line 323. No need to reinvent it.

2023-06-20 16:00 UTC, carloleo commented
Hi @IvanNardi 

thank you for your comment.

I had seen where the attributes are parsed, but I opted for a function because of what I commented at line 337 (`stun.c`). 
Please see the mail that I sent to _team@ntop.otg_.

2023-06-20 16:05 UTC, lucaderi commented
@carloleo As @IvanNardi we cannot merge your code as it is a duplicate of the existing one, making nDPI unmaintainable. Please update the code as instructed.

2023-06-20 16:13 UTC, IvanNardi commented on src/lib/protocols/stun.c
> +          break;
This is likely an unrelated issue that we can address later: right now we end the dissection when we have a valid sub-proto (whatsapp Call in this case); we might need to keep parsing more pkts/attributes looking for more metadata.

Anyway, for the time being, to test your code simply use a pcap with only one Allocate Response pkt

2023-06-20 18:24 UTC, IvanNardi commented
@carloleo
1) could you take a look at the build failure in the CI, please? [some warnings to fix]
2) could you add ipv6 support, too?

2023-06-20 19:08 UTC, carloleo commented
@IvanNardi 

I added the attributes to `struct ndpi_flow_struct`, but this violated the constraint on the size.
![image](https://github.com/ntop/nDPI/assets/50950273/285f4a80-77eb-45aa-b470-130d9361e71d)

2023-06-20 19:10 UTC, IvanNardi commented
> @IvanNardi
> 
> I added the attributes to `struct ndpi_flow_struct`, but this violated the constraint on the size. ![image](https://user-images.githubusercontent.com/50950273/247235046-285f4a80-77eb-45aa-b470-130d9361e71d.png)

Let's try updating the "952" constant to 960....

2023-12-22 14:35 UTC, IvanNardi commented
[6 months later...] STUN code is quite different now... if you are still interested in a similar feature, please open a new PR, please

2023-12-22 14:35 UTC, closed without merging