added feature to extract filename from http attachment
ntop/nDPI pull request #2037
Opened 2023-07-07 08:51 UTC by ChiaraMaggi

2023-07-07 09:38 UTC, IvanNardi requested changes
Hi @ChiaraMaggi, thanks for your contribution.
Unfortunately, as you can see from the CI results, there are multiple issues...
Let's start try fixing the compilation
* in `src/include/ndpi_typedefs.h` replace 952 with 960. You can test it yourself running `make check` in your machine

Some other comments below:

2023-07-07 09:38 UTC, IvanNardi commented on src/lib/protocols/http.c
> +    flow->http.filename = (char*)malloc((filename_len-3)*sizeof(char));
* you need to check for allocation failure
* use `ndpi_malloc`

2023-07-07 09:38 UTC, IvanNardi commented on src/lib/protocols/http.c
> +    //case: filename="file_name"
There is no guarantee that if the filename starts with `"` it ends with `"` too

2023-07-07 09:38 UTC, IvanNardi commented on src/lib/protocols/http.c
> +    flow->http.filename = (char*)malloc((filename_len-1)*sizeof(char));
As above

2023-07-07 10:11 UTC, IvanNardi commented on src/lib/protocols/http.c
> +  flow->http.filename = strncpy(flow->http.filename, (char*)packet->content_disposition_line.ptr+attachment_len, filename_len);
Sorry if I wasn't clear... it seems right to strip the initial and the final `"` from the name, but you need to check both of them and remove the characters only if really present

2023-07-11 16:30 UTC, IvanNardi reviewed
Definitely better. Just some small issues

2023-07-11 16:30 UTC, IvanNardi commented on src/lib/protocols/http.c
> +		//return(flow->category);
Please, remove the line (instead of adding a comment)

2023-07-11 16:30 UTC, IvanNardi commented on src/lib/protocols/http.c
> +      flow->http.filename = ndpi_malloc(filename_len);
All these `ndpi_malloc` might fail. You need to check that here and below

2023-07-11 16:30 UTC, IvanNardi commented on src/lib/protocols/http.c
> +      flow->http.filename = ndpi_malloc(filename_len-1);
here

2023-07-11 16:30 UTC, IvanNardi commented on src/lib/protocols/http.c
> +    flow->http.filename = ndpi_malloc(filename_len+1);
and here

2023-07-11 18:22 UTC, IvanNardi approved these changes

2023-07-11 20:43 UTC, lucaderi commented on src/lib/protocols/http.c
> +      flow->http.filename = strncpy(flow->http.filename, (char*)packet->content_disposition_line.ptr+attachment_len, filename_len);
Assignment not necessary

2023-07-11 20:44 UTC, lucaderi commented on src/lib/protocols/http.c
> +        flow->http.filename = strncpy(flow->http.filename, (char*)packet->content_disposition_line.ptr+attachment_len+1, filename_len-2);
Assignment not necessary

2023-07-11 20:44 UTC, lucaderi commented on src/lib/protocols/http.c
> +        flow->http.filename = strncpy(flow->http.filename, (char*)packet->content_disposition_line.ptr+attachment_len+1, filename_len-1);
Assignment not necessary

2023-07-11 20:45 UTC, merged