add ethereum protocol dissector.
ntop/nDPI pull request #2111
Opened 2023-10-23 19:54 UTC by mmaatuq

as explained here for bitcoin https://www.ntop.org/guides/nDPI/protocols.html#ndpi-protocol-bitcoin the same is applicable for ethereum.
ethereum detection was removed from mining protocol and is now handled separately.

Please sign (check) the below before submitting the Pull Request:

- [ x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x ] I have read the contributing guidelines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [ ] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:
- move ethereum detection from mining protocol to a standalone ethereum protocol dissector. 
- update ethereum_ip_addresses_download.sh to have  NDPI_ETHEREUM_PRTOCOL instead of NDPI_MINING_PRTOCOL.
- update test cases.

2023-10-24 00:06 UTC, utoni commented on src/lib/protocols/ethereum.c
> +static void ndpi_ehter_cache_connection(struct ndpi_detection_module_struct *ndpi_struct,
Typ0? :)

```suggestion
static void ndpi_ether_cache_connection(struct ndpi_detection_module_struct *ndpi_struct,
```

2023-10-24 00:06 UTC, utoni commented on tests/cfgs/default/result/ethereum.pcap.out
> +	1	TCP 192.168.1.184:56625 -> 5.1.83.226:30303 [proto: 0/Unknown][IP: 0/Unknown][ClearText][Confidence: Unknown][DPI packets: 2][2 pkts/156 bytes -> 0 pkts/0 bytes][Goodput ratio: 0/0][1.10 sec][Risk
Couldn't that flow also be Ethereum related?

2023-10-24 00:06 UTC, utoni commented on src/lib/protocols/ethereum.c
> +     && ((source == 30303) || (dest == 30303))
Are you sure that Ethereum uses fixed ports?
The discovery protocol dissector seems not to rely on such.

2023-10-24 00:06 UTC, utoni commented on src/lib/protocols/ethereum.c
> +  return(((dport >= 30300) && (dport <= 30305)) ? 1 : 0);
same here

2023-10-24 06:43 UTC, mmaatuq commented on src/lib/protocols/ethereum.c
> +     && ((source == 30303) || (dest == 30303))
- I'm not sure about this, I took this piece of logic as it's from the mining protocol, I'll double check on this and if it's not true, will change it.

2023-10-24 11:06 UTC, utoni commented
Please rebase to the `dev` branch and fix merge conflicts.

It is also mandatory to add a new entry to `doc/protocols.rst`.

2023-10-24 20:11 UTC, mmaatuq commented on src/lib/protocols/ethereum.c
> +     && ((source == 30303) || (dest == 30303))
- I checked this one and I found that this port is the default port for ethereum discovery protocol.
- [stack overflow answer](https://ethereum.stackexchange.com/questions/809/which-tcp-and-udp-ports-are-required-to-run-an-ethereum-client)
- [ethereum developer](https://ethereum.org/en/developers/docs/networking-layer/network-addresses/#:~:text=58.6%20%2C%20TCP%20port%2030303%20and%20UDP%20discovery%20port%2030301%20.)

- also [here](https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go) the same port is used for botnodes ( default nodes that help the client discover other peers when this client's first time to connect to the ethereum network) 
- still from the protocol specification [here](https://github.com/ethereum/devp2p/blob/master/discv4.md) they don't mention anything about used ports 
-  if we removed it, we only left with lengths which is not a strong indication. 
- this was there (as part of the mining protocol) and no complaints about it yet.
- we can have a ticket for later to improve the detection and find other strong patterns, and we can then remove the port.

2023-10-25 08:39 UTC, IvanNardi requested changes
Same small issues..

2023-10-25 08:39 UTC, IvanNardi commented on src/lib/protocols/ethereum.c
> + * Copyright (C) 2018-22 - ntop.org
(C) 2023 - ntop.org

2023-10-25 08:39 UTC, IvanNardi commented on src/lib/protocols/ethereum.c
> +      ndpi_snprintf(flow->protos.mining.currency, sizeof(flow->protos.mining.currency), "%s", "ETH");
Remove that line, please. We can safely write to `flow->protos.mining` only if the classification is `NDPI_PROTOCOL_MINING`. Furthermore, we now know the exact crypto currency via the new protocol id

2023-10-25 08:39 UTC, IvanNardi commented on src/lib/protocols/ethereum.c
> +       ndpi_snprintf(flow->protos.mining.currency, sizeof(flow->protos.mining.currency), "%s", "ETH");
same here

2023-10-25 08:39 UTC, IvanNardi commented on src/lib/protocols/ethereum.c
> +      ndpi_snprintf(flow->protos.mining.currency, sizeof(flow->protos.mining.currency), "%s", "ETH");
and here

2023-10-25 09:35 UTC, IvanNardi approved these changes
Fine for me. What about you, @utoni ?

2023-10-25 09:50 UTC, utoni commented
> Fine for me. What about you, @utoni ?

Same. Only a rebase to `dev` is missing. :)

2023-10-25 09:52 UTC, utoni approved these changes
Great work @mmaatuq!

2023-10-25 10:44 UTC, merged

2023-10-25 10:44 UTC, IvanNardi commented
@mmaatuq , thank you very much!