Improve CORBA detection
ntop/nDPI pull request #2167
Opened 2023-11-25 12:07 UTC by 0xA50C1A1

Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

Added additional checks for Zipped Inter-ORB Protocol (ZIOP) and Unreliable Multicast Inter-ORB Protocol (MIOP, CORBA over UDP).

2023-11-26 15:07 UTC, utoni commented on tests/cfgs/default/result/ziop.pcap.out
> +	1	TCP [::1]:51399 <-> [::1]:57998 [proto: 0/Unknown][IP: 0/Unknown][ClearText][Confidence: Unknown][DPI packets: 6][4 pkts/352 bytes <-> 2 pkts/180 bytes][Goodput ratio: 0/0][< 1 sec][bytes ratio: 0
Is that undetected flow the intended behavior?

2023-11-26 15:25 UTC, 0xA50C1A1 commented on tests/cfgs/default/result/ziop.pcap.out
> +	1	TCP [::1]:51399 <-> [::1]:57998 [proto: 0/Unknown][IP: 0/Unknown][ClearText][Confidence: Unknown][DPI packets: 6][4 pkts/352 bytes <-> 2 pkts/180 bytes][Goodput ratio: 0/0][< 1 sec][bytes ratio: 0
Yea, I forgot to delete this flow from the pcap file:
![Снимок экрана от 2023-11-26 18-22-24](https://github.com/ntop/nDPI/assets/105977161/bd63c5c8-fe7c-422d-8589-068a86226ebb)

2023-11-27 10:10 UTC, IvanNardi requested changes
If there isn't any specific reasons, could you restore the `corba.pcap` test, please?
If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?

2023-11-27 11:20 UTC, 0xA50C1A1 commented
> If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?

No problem, I did it.

2023-11-27 11:26 UTC, IvanNardi commented
> > If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?
> 
> No problem, I did it.

If I am not mistaken, there isn't the flow with the "ZIOP" pattern in the file... Might be useful to add it, if possible?

2023-11-27 11:33 UTC, 0xA50C1A1 commented
> > > If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?
> > 
> > 
> > No problem, I did it.
> 
> If I am not mistaken, there isn't the flow with the "ZIOP" pattern in the file... Might be useful to add it, if possible?

Here it is. But this may not be the best sample of ZIOP traffic, since here this packet is the last one in the flow.
![Снимок экрана от 2023-11-27 14-30-00](https://github.com/ntop/nDPI/assets/105977161/ae6b2a6d-9dac-48b1-bac7-1566f896b503)

2023-11-27 11:38 UTC, IvanNardi commented
> > > > If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?
> > > 
> > > 
> > > No problem, I did it.
> > 
> > 
> > If I am not mistaken, there isn't the flow with the "ZIOP" pattern in the file... Might be useful to add it, if possible?
> 
> Here it is. But this may not be the best sample of ZIOP traffic, since here this packet is the last one in the flow. ![Снимок экрана от 2023-11-27 14-30-00](https://private-user-images.githubusercontent.com/105977161/285849198-ae6b2a6d-9dac-48b1-bac7-1566f896b503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODUzOTgsIm5iZiI6MTcwMTA4NTA5OCwicGF0aCI6Ii8xMDU5NzcxNjEvMjg1ODQ5MTk4LWFlNmIyYTZkLTlkYWMtNDhiMS1iYWM3LTE1NjZmODk2YjUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMTM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFiNGUyMjFhYmVhYjQzZjEwZDE3ZGQ1Mjk3ODkwZDcwYzc3MDk0OTc4ZDNhMjJjNGY4YzJkYjgyZDg1NWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3pA-2dOTYHQeYGzZ_DOFgDXU3gmzDxzpH-3GRNk6n9A)

Ok, that'll do fine for the time being

2023-11-27 11:39 UTC, IvanNardi approved these changes

2023-11-27 11:43 UTC, 0xA50C1A1 commented
> > > > > If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?
> > > > 
> > > > 
> > > > No problem, I did it.
> > > 
> > > 
> > > If I am not mistaken, there isn't the flow with the "ZIOP" pattern in the file... Might be useful to add it, if possible?
> > 
> > 
> > Here it is. But this may not be the best sample of ZIOP traffic, since here this packet is the last one in the flow. ![Снимок экрана от 2023-11-27 14-30-00](https://private-user-images.githubusercontent.com/105977161/285849198-ae6b2a6d-9dac-48b1-bac7-1566f896b503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODUzOTgsIm5iZiI6MTcwMTA4NTA5OCwicGF0aCI6Ii8xMDU5NzcxNjEvMjg1ODQ5MTk4LWFlNmIyYTZkLTlkYWMtNDhiMS1iYWM3LTE1NjZmODk2YjUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMTM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFiNGUyMjFhYmVhYjQzZjEwZDE3ZGQ1Mjk3ODkwZDcwYzc3MDk0OTc4ZDNhMjJjNGY4YzJkYjgyZDg1NWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3pA-2dOTYHQeYGzZ_DOFgDXU3gmzDxzpH-3GRNk6n9A)
> 
> Ok, that'll do fine for the time being



> > > > > If there isn't any specific reasons, could you restore the `corba.pcap` test, please? If you are able, could you try to merge these 3 files `corba.pcap`, `miop.pcap` and `ziop.pcap` into only one trace, called `corba.pcap`?
> > > > 
> > > > 
> > > > No problem, I did it.
> > > 
> > > 
> > > If I am not mistaken, there isn't the flow with the "ZIOP" pattern in the file... Might be useful to add it, if possible?
> > 
> > 
> > Here it is. But this may not be the best sample of ZIOP traffic, since here this packet is the last one in the flow. ![Снимок экрана от 2023-11-27 14-30-00](https://private-user-images.githubusercontent.com/105977161/285849198-ae6b2a6d-9dac-48b1-bac7-1566f896b503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODUzOTgsIm5iZiI6MTcwMTA4NTA5OCwicGF0aCI6Ii8xMDU5NzcxNjEvMjg1ODQ5MTk4LWFlNmIyYTZkLTlkYWMtNDhiMS1iYWM3LTE1NjZmODk2YjUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMTM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFiNGUyMjFhYmVhYjQzZjEwZDE3ZGQ1Mjk3ODkwZDcwYzc3MDk0OTc4ZDNhMjJjNGY4YzJkYjgyZDg1NWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3pA-2dOTYHQeYGzZ_DOFgDXU3gmzDxzpH-3GRNk6n9A)
> 
> Ok, that'll do fine for the time being

I guess this could be useful for detecting mid-flows.

2023-11-27 12:10 UTC, merged

2023-11-27 12:11 UTC, IvanNardi commented
Thanks!