Add ANSI C12.22 protocol dissector
ntop/nDPI pull request #2317
Opened 2024-02-14 16:32 UTC by 0xA50C1A1

Please sign (check) the below before submitting the Pull Request:

- [ ] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [ ] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [ ] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

This protocol is used to communicate with electric meters. PCAP example is taken from the Wireshark wiki.

2024-02-14 19:29 UTC, IvanNardi requested changes
Just a minor issue.
This is  a trace with udp traffic [ansic12.12_udp.zip](https://github.com/ntop/nDPI/files/14285216/ansic12.12_udp.zip)
Could you double check that is is properly classified (it seems so to me) and merge part of it with your tcp trace, please?

2024-02-14 19:29 UTC, IvanNardi commented on src/lib/protocols/c1222.c
> +      ((u_int16_t)(packet->payload_packet_len-2) != packet->payload[1]))
(u_int8_t)

2024-02-14 19:31 UTC, 0xA50C1A1 commented
> Just a minor issue. This is a trace with udp traffic [ansic12.12_udp.zip](https://github.com/ntop/nDPI/files/14285216/ansic12.12_udp.zip) Could you double check that is is properly classified (it seems so to me) and merge part of it with your tcp trace, please?

You found the UDP trace? Thank you so much.

Yeah, I'll fix all the issues in a moment.

2024-02-15 08:35 UTC, IvanNardi approved these changes
Thanks (also for removing the skype leftovers...)

2024-02-15 08:36 UTC, merged