#181: nDPI: Commit nDPI Version 02.29.2024.1
ntop/nDPI pull request #2333
Opened 2024-03-01 03:19 UTC by akumartrapp

Please sign (check) the below before submitting the Pull Request:

- [ ] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [ ] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [ ] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/nDPI/issues):

Describe changes:

2024-03-04 16:02 UTC, IvanNardi commented
@akumartrapp, are you sure you pushed this code to the right repository? It seems this PR is meant for a your personal fork...

2024-03-05 05:30 UTC, utoni requested changes
I do not understand what the idea of the PR was.
Did you want to replace the old JSON serialization or process pcap files from a directory recursively or both or something else?

2024-03-05 05:30 UTC, utoni commented on example/ReadJson.c
> +    if (readlink("/proc/self/exe", buffer, size) == -1) {
won't work on mac

2024-03-05 05:30 UTC, utoni commented on example/ReadJson.c
> +                (*paramsVector)[*vectorSize - 1].sourceIP = _strdup("NOT_SET");
Why even set those keys?

2024-03-05 05:30 UTC, utoni commented on example/ndpiReader.c
> -         "  -R                        | Print detected realtime protocols\n"
???

2024-03-05 05:30 UTC, utoni commented on example/ndpiReader.c
> +     // _pcap_file[0] = optarg;  // Ashwani: This is commented out as we take pcap/pcapng files from the input folder which is set using option '-R'
???

2024-03-05 05:30 UTC, utoni commented on example/ndpiReader.c
> +        pCapFilesFolderLocationPath = optarg; // Ashwani: This is folder path of pcap/pcapng files
What happened to the old option?

2024-03-11 09:21 UTC, IvanNardi commented
@akumartrapp, any updates?

2024-04-04 21:54 UTC, utoni commented
Closing for inactivity. Please re-open if you still want to get this patch into `dev`.

2024-04-04 21:54 UTC, closed without merging