Added protocol - JRMI - Java Remote Method Invocation
ntop/nDPI pull request #2470
Opened 2024-06-13 15:48 UTC by dandare100

Please sign (check) the below before submitting the Pull Request:

- [X] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [X] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [X] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

Added JRMI protocol.

https://docs.oracle.com/en/java/javase/21/docs/specs/rmi/protocol.html

2024-06-13 15:57 UTC, IvanNardi commented
Not sure why CI tests are not triggered... It happened also with your previous PR...
Try to close and re-open...

2024-06-13 18:53 UTC, IvanNardi commented
> Not sure why CI tests are not triggered... It happened also with your previous PR... Try to close and re-open...

@dandare100, are you pushing via API, using `GITHUB_TOKEN`?

2024-06-14 07:24 UTC, IvanNardi requested changes
As reported by the CI:
* you need to update the tests results
* could you fix the window build? You need to add the new c file in `windows/nDPI.vcxproj`

Some other minor issues below

2024-06-14 07:24 UTC, IvanNardi commented on src/include/ndpi_protocol_ids.h
> +  NDPI_PROTOCOL_JRMI                  = 416, /*https://docs.oracle.com/en/java/javase/21/docs/specs/rmi/protocol.html*/
Remove the comment, please. You already added it in the documentation

2024-06-14 07:24 UTC, IvanNardi commented on src/lib/protocols/jrmi.c
> + * Copyright (C) 2011-24 - ntop.org
Copyright (C) 2024 - ntop.org

2024-06-14 07:24 UTC, IvanNardi commented on src/lib/protocols/jrmi.c
> +					 /* ndpi_protocol_type_t protocol_type */) {
I know that you likely "copied" this code from somewhere else, but could you remove the third parameter, please?

2024-06-14 07:24 UTC, IvanNardi commented on src/lib/protocols/jrmi.c
> +	if (packet->tcp != NULL) {
You can remove this check. We are sure that only TCP packets trigger this code

2024-06-14 07:24 UTC, IvanNardi commented on src/lib/protocols/jrmi.c
> +			     struct ndpi_packet_struct *packet = &ndpi_struct->packet;
Indentation

2024-06-14 07:24 UTC, IvanNardi commented on src/lib/protocols/jrmi.c
> +	if(flow->packet_counter > 5)
You can remove the check and always exclude the protocol here
AFSIU, the magic word + version fields are present only in the first packet of the flow. If we miss it, we will never find them again

2024-06-14 07:26 UTC, dandare100 commented
> > Not sure why CI tests are not triggered... It happened also with your previous PR... Try to close and re-open...
> 
> @dandare100, are you pushing via API, using `GITHUB_TOKEN`?

Hello there @IvanNardi 

I push to my nDPI fork (using an ssh key) and create the pull request on the github interface.
Should I change it to another way ?

Jeff

2024-06-14 07:28 UTC, IvanNardi commented
> > > Not sure why CI tests are not triggered... It happened also with your previous PR... Try to close and re-open...
> > 
> > 
> > @dandare100, are you pushing via API, using `GITHUB_TOKEN`?
> 
> Hello there @IvanNardi
> 
> I push to my nDPI fork (using an ssh key) and create the pull request on the github interface. Should I change it to another way ?
> 
> Jeff

No you don't; it seems right. I was trying to understand why your commit/push/close-open doesn't trigger the GH Actions...

2024-06-14 07:33 UTC, dandare100 commented
PS : Apologies for the up and down on the commits. I missed the MS Visual studio stuff

2024-06-14 07:35 UTC, dandare100 commented on src/include/ndpi_protocol_ids.h
> +  NDPI_PROTOCOL_JRMI                  = 416, /*https://docs.oracle.com/en/java/javase/21/docs/specs/rmi/protocol.html*/
Will do

2024-06-14 07:35 UTC, dandare100 commented on src/lib/protocols/jrmi.c
> + * Copyright (C) 2011-24 - ntop.org
will do

2024-06-14 07:35 UTC, dandare100 commented on src/lib/protocols/jrmi.c
> +					 /* ndpi_protocol_type_t protocol_type */) {
100 %

2024-06-14 07:36 UTC, dandare100 commented on src/lib/protocols/jrmi.c
> +	if (packet->tcp != NULL) {
Understood

2024-06-14 07:36 UTC, dandare100 commented on src/lib/protocols/jrmi.c
> +	if(flow->packet_counter > 5)
Understood

2024-06-14 08:09 UTC, dandare100 commented
@IvanNardi 

I am not sure of the correct procedure to update tests as requested.
I have added a pcap and checked in the jrmi.pcap.out file.

I get an error on step 7 

```
Be sure to have nBPF support, cloning PF_RING in the same directory where you cloned nDPI: git clone https://github.com/ntop/PF_RING/ && cd PF_RING/userland/nbpf && ./configure && make
```
```
gcc -Wall -fPIC -O2 -I../lib -I../../kernel  -Wno-address-of-packed-member   -g nbpftest.c -o nbpftest  libnbpf.a `../lib/pfring_config --libs` -lpthread -lm 
/bin/sh: 1: ../lib/pfring_config: not found
```

2024-06-14 08:26 UTC, IvanNardi commented
> ./lib/pfring_config: not found

You can ignore this error, because `linbbpf.a` has been created. I'll update the documentation to make that clear

In your specific case, at point 10, you can run `NDPI_FORCE_UPDATING_UTESTS_RESULTS=1 ./tests/do.sh` to update all the tests: "git add" the results

2024-06-14 18:27 UTC, dandare100 commented
Hello there @IvanNardi 
I have run the tests and there is no change to the original tests/cfgs/default/result/jrmi.pcap.out. 
Anything else I need to do ? 
I assume I must not add all the test results

2024-06-14 18:39 UTC, IvanNardi commented
> I assume I must not add all the test results

That's exactly what you need to do :)
Your code triggers a (slightly) change in (almost) all the tests: we need to update all the results

2024-06-14 18:44 UTC, dandare100 commented
Eish. lol, my bad. I didn't want to blat over everyone's work. Done.

2024-06-14 19:42 UTC, IvanNardi approved these changes
I pushed some tiny changes.
Thanks for this contribution and for your patience!

2024-06-14 20:10 UTC, dandare100 commented
You are very welcome and thank you too

2024-06-15 08:52 UTC, merged