Slightly better ndpi_strrstr implementation
ntop/nDPI pull request #2570
Opened 2024-09-24 16:48 UTC by 0xA50C1A1

Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guidelines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

Nothing fancy, just added a couple of checks and made the code more readable.

@pasabanov @IvanNardi what do you think?

2024-09-24 17:43 UTC, IvanNardi approved these changes

2024-09-25 10:24 UTC, pasabanov requested changes

2024-09-25 10:24 UTC, pasabanov commented on src/lib/ndpi_utils.c
> +    return (char*) haystack;
Should return `(char*) haystack + strlen(haystack)` here.

2024-09-25 10:30 UTC, 0xA50C1A1 commented on src/lib/ndpi_utils.c
> +    return (char*) haystack;
Done.

2024-09-25 10:41 UTC, pasabanov requested changes

2024-09-25 10:41 UTC, pasabanov commented on src/lib/ndpi_utils.c
> +  return last_occurrence;
I guess

```c
const char *last_occurrence = NULL;
...
last_occurrence = current_pos;
...
return (char*) last_occurrence;
```

might be slightly better.

2024-09-25 18:45 UTC, pasabanov approved these changes

2024-09-25 18:49 UTC, IvanNardi approved these changes

2024-09-25 18:49 UTC, merged

2024-09-25 18:49 UTC, IvanNardi commented
Thanks everyone