Add support Yandex Alice
ntop/nDPI pull request #2633
Opened 2024-11-28 18:46 UTC by Klavishnik

Please sign (check) the below before submitting the Pull Request:

-  I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
-  I have read the contributing guidelines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
-  I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/nDPI/issues):

Describe changes:
Add support Yandex Alice

2024-11-28 19:35 UTC, IvanNardi requested changes
Thanks for your contribution. Could you please:
* sign the CLA?
* add an example of this traffic? One simple TLS flow (the first 6-7 pkts only) to any of this domains is enough. It would be wonderful if you could merge it with the existing `tests/pcaps/sites2.pcap` file

2024-11-28 19:35 UTC, IvanNardi commented on src/lib/ndpi_content_match.c.inc
> +   { "quasar.yandex.ru",                 "YandexAlice", NDPI_PROTOCOL_YANDEX_ALICE, NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT, NDPI_PROTOCOL_ACCEPTABLE, NDPI_PROTOCOL_DEFAULT_LEVEL },
Duplicate. Remove it

2024-11-28 20:49 UTC, Klavishnik commented on src/lib/ndpi_content_match.c.inc
> +   { "quasar.yandex.ru",                 "YandexAlice", NDPI_PROTOCOL_YANDEX_ALICE, NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT, NDPI_PROTOCOL_ACCEPTABLE, NDPI_PROTOCOL_DEFAULT_LEVEL },
Здравствуйте!
Яндекс Алиса - это голосовой ассистент, который в основном используется в умных станциях, несмотря на то, что её функции доступен на сайте, браузере и в приложении Яндекса. Возможно не нужно объединять тестовый пример трафика Яндекс Алисы с файлом `sites2.pcap`? 

Прикладываю пример захваченного трафика в виде файла , а так результат его разбора через `ndpiReader`

[yandex-alice.zip](https://github.com/user-attachments/files/17952236/yandex-alice.zip)

![1](https://github.com/user-attachments/assets/99d2ee54-2571-4be0-9d3b-1b51a8b539ba)

2024-11-28 20:52 UTC, Klavishnik commented on src/lib/ndpi_content_match.c.inc
> +   { "quasar.yandex.ru",                 "YandexAlice", NDPI_PROTOCOL_YANDEX_ALICE, NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT, NDPI_PROTOCOL_ACCEPTABLE, NDPI_PROTOCOL_DEFAULT_LEVEL },
Remove duplicate in new commit

2024-11-28 20:56 UTC, Klavishnik commented on src/lib/ndpi_content_match.c.inc
> +   { "quasar.yandex.ru",                 "YandexAlice", NDPI_PROTOCOL_YANDEX_ALICE, NDPI_PROTOCOL_CATEGORY_VIRTUAL_ASSISTANT, NDPI_PROTOCOL_ACCEPTABLE, NDPI_PROTOCOL_DEFAULT_LEVEL },
I signed the CLI through the google form

2024-11-29 13:13 UTC, merged

2024-11-29 13:13 UTC, IvanNardi commented
Thanks for your contribution, @Klavishnik