Added detection of OnSatMail service packets
ntop/nDPI pull request #276
Opened 2016-10-14 09:35 UTC by linusoft

2016-10-14 12:58 UTC, kYroL01 commented
I'm going to test it

2016-10-14 14:39 UTC, kYroL01 commented
I think the pull is correct, but before merging I have some question:
1) you check if the packet has the IP `flow->packet.iph`. How can a packet doesn't have the ip address ?
2) do u have any other information (payload lenght, if protocol is over TCP or UDP) to put in the dissector ?
3) is better create a variable `struct ndpi_packet_struct *packet` and initialize to `&flow->packet`. In this way all the checks are doing on this packet, avoiding any (possibile) crush on the flow original structure (I can change this part after the merge).

Thank you

2016-11-28 17:19 UTC, alagoutte requested changes

2016-11-28 17:19 UTC, alagoutte commented on src/lib/Makefile.am
> +                     protocols/onsatmail.c \
it is sort by name

2016-11-28 17:19 UTC, alagoutte commented on src/lib/ndpi_content_match.c.inc
> +  { 0x40048DF7 /* 64.4.141.247/32 */, 32, NDPI_SERVICE_ONSATMAIL },
only 1 IP ?

2016-11-28 17:19 UTC, alagoutte commented on src/lib/protocols/onsatmail.c
> +		u_int16_t dport;
variable never used

2016-11-28 17:19 UTC, alagoutte commented on src/lib/protocols/onsatmail.c
> +		u_int16_t sport;
same issue

2016-11-28 17:24 UTC, kYroL01 commented
I'm agree with @alagoutte . This is why I cannot still merge this pull request

2016-11-28 17:30 UTC, closed without merging